name: build

on: [push, pull_request]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Test
        run: ./gradlew build

  publish:
    runs-on: ubuntu-latest
    if: contains(github.ref, '/tags/v')
    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Upload Artifacts
        run: |
          ./gradlew publishMavenPublicationToSonatypeRepository \
            -Ppablo.repository.maven.name=Sonatype \
            -Ppablo.repository.maven.url=https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/ \
            -Ppablo.repository.maven.username=${{ secrets.SONATYPE_USERNAME }} \
            -Ppablo.repository.maven.password=${{ secrets.SONATYPE_PASSWORD }} \
            -Ppablo.signing.keyId=${{ secrets.SIGNING_KEY_ID }} \
            -Ppablo.signing.password=${{ secrets.SIGNING_PASSWORD }} \
            -Ppablo.signing.secretKey='${{ secrets.SIGNING_SECRET_KEY }}'
